spring:
    application:
        name: candidate-service
    cloud:
        config:
            enabled: false
    datasource:
        url: jdbc:postgresql://localhost:5434/candidate_db
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092

    # Configuration de Feign
feign:
    client:
        config:
            default:
                connectTimeout: 30000
                readTimeout: 600000
                loggerLevel: basic
            ai-service:
                connectTimeout: 30000
                readTimeout: 600000
    httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50

server:
    port: 8083

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

# Fichier: src/main/resources/application.yml (ajouter à la fin)
job:
    service:
        url: http://job-service:8082 # URL du Job Service

ai:
    service:
        url: http://ai-service:8084 # URL du AI Service
